#!/bin/bash
pathforthesis=$HOME/phd-thesis
for f in $pathforthesis/*.odt;
do
fn=${f%.odt}
libreoffice --convert-to txt --outdir $HOME/data $f 
done
F=$(basename $fn)
WC=$(wc -w $HOME/data/$F.txt | cut -d ' ' -f 1)
echo $WC > $HOME/data/phdwords 
exit 0
