#!/bin/sh
sq='\xe2\x96\xa0'
sed -r  -e 's/\B\@(\w+)/\$\{color 9987ed\}\1\$\{color\}/g' -e 's/\B\#(\w+)/\$\{color AE9961\}\1\$\{color\}/g' -e "s/(\[ui\])/\$\{color ffcccc\}"$sq"\$\{color\}\ \$\{color ccffcc\}"$sq"\$\{color\}/g" -e "s/(\[uI\])/\$\{color ffcccc\}"$sq"\$\{color\}\ \$\{color 00ff00\}"$sq"\$\{color\}/g" -e "s/(\[Ui\])/\$\{color ff0000\}"$sq"\$\{color\}\ \$\{color ccffcc\}"$sq"\$\{color\}/g" -e "s/(\[UI\])/\$\{color ff0000\}"$sq"\$\{color\}\ \$\{color 00ff00\}"$sq"\$\{color\}/g" -e 's/(due:)((19|20)[0-9-]{8})/\$\{color 99AE61\}\2\$\{color\}/g' $CMDATA/tasks > $CMDATA/conkytasklist
cat $CMDATA/conkytasklist
exit 0
